In [19]:
import numpy as np
import pandas as pd

In [20]:
list1 = [20, 30, 40]
list1

[20, 30, 40]

In [21]:
arr1 = np.array(list1)
arr1

array([20, 30, 40])

In [22]:
list1 * 3

[20, 30, 40, 20, 30, 40, 20, 30, 40]

In [23]:
arr1 * 3

array([ 60,  90, 120])

In [24]:
list2 = [list1, list1]
list2

[[20, 30, 40], [20, 30, 40]]

In [25]:
arr2 = np.array(list2)
arr2[0]

array([20, 30, 40])

In [26]:
x = pd.Series([10,20,30,40])
x

0    10
1    20
2    30
3    40
dtype: int64

In [27]:
data = [['Adrian', 20],['Bethany', 23],['Chloe',41]]
df = pd.DataFrame(data, columns=['Name', 'Age'])

In [28]:
df.fillna(0)

Name  Age
0   Adrian   20
1  Bethany   23
2    Chloe   41

In [29]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [33]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [34]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

df

A         B         C         D
2013-01-01  0.510584  0.555810 -1.337518  0.415514
2013-01-02  0.293359  0.294350 -0.181170 -0.443929
2013-01-03 -0.437107 -0.100399 -1.090400  0.557961
2013-01-04  0.682945  0.720717  0.901945 -1.862558
2013-01-05 -0.082882 -1.519918 -1.157155  1.813987
2013-01-06 -0.002910  0.022147 -1.060357  1.057815

In [44]:
df.loc[:, ["A", "B"]]

A         B
2013-01-01  0.510584  0.555810
2013-01-02  0.293359  0.294350
2013-01-03 -0.437107 -0.100399
2013-01-04  0.682945  0.720717
2013-01-05 -0.082882 -1.519918
2013-01-06 -0.002910  0.022147

In [45]:
df.iloc[0:3]

A         B         C         D
2013-01-01  0.510584  0.555810 -1.337518  0.415514
2013-01-02  0.293359  0.294350 -0.181170 -0.443929
2013-01-03 -0.437107 -0.100399 -1.090400  0.557961